FIX: Fix missing uint8_t declaration
In file included from /run/build/BambuStudio/src/slic3r/Utils/CertificateVerify.cpp:1:
/run/build/BambuStudio/src/slic3r/Utils/CertificateVerify.hpp:10:20: error: ‘uint8_t’ was not declared in this scope
   10 |         std::array<uint8_t, 32> cert_sha256;
      |                    ^~~~~~~