FIX: Fix missing ClipperLib_Z type definition
In file included from /run/build/BambuStudio/src/libslic3r/OverhangDetector.cpp:1:
/run/build/BambuStudio/src/libslic3r/OverhangDetector.hpp:8:16: error: ‘ClipperLib_Z’ does not name a type
    8 | using ZPoint = ClipperLib_Z::IntPoint;
      |                ^~~~~~~~~~~~
/run/build/BambuStudio/src/libslic3r/OverhangDetector.hpp:9:15: error: ‘ClipperLib_Z’ does not name a type
    9 | using ZPath = ClipperLib_Z::Path;
      |               ^~~~~~~~~~~~
/run/build/BambuStudio/src/libslic3r/OverhangDetector.hpp:10:16: error: ‘ClipperLib_Z’ does not name a type
   10 | using ZPaths = ClipperLib_Z::Paths;
      |                ^~~~~~~~~~~~