FIX: Fix missing Slic3r::BoundingBox type declaration
In file included from /run/build/BambuStudio/src/libslic3r/ExtrusionEntityCollection.hpp:6,
                 from /run/build/BambuStudio/src/libslic3r/CurveAnalyzer.hpp:4,
                 from /run/build/BambuStudio/src/libslic3r/CurveAnalyzer.cpp:1:
/run/build/BambuStudio/src/libslic3r/ExtrusionEntity.hpp:33:17: error: field ‘bbox’ has incomplete type ‘Slic3r::BoundingBox’
   33 |     BoundingBox bbox;
      |                 ^~~~