Fix Slic3r::BoundingBox declaration
[120/471] Building CXX object src/libslic3r/CMakeFiles/libslic3r.dir/GCode/RetractWhenCrossingPerimeters.cpp.o
FAILED: src/libslic3r/CMakeFiles/libslic3r.dir/GCode/RetractWhenCrossingPerimeters.cpp.o
/run/ccache/bin/c++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CHRONO_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_IOSTREAMS_NO_LIB -DBOOST_LOCALE_NO_LIB -DBOOST_LOG_NO_LIB -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -DHAVE_FREETYPE -DHAVE_OPENGL_EXT -DHAVE_XLIB -DLIBNEST2D_GEOMETRIES_libslic3r -DLIBNEST2D_OPTIMIZER_nlopt -DLIBNEST2D_STATIC -DLIBNEST2D_THREADING_tbb -DOCC_CONVERT_SIGNALS -DOPENVDB_OPENEXR_STATICLIB -DOPENVDB_STATICLIB -DSLIC3R_GUI -DTBB_USE_CAPTURED_EXCEPTION=0 -DUNICODE -DUSE_TBB -DWXINTL_NO_GETTEXT_MACRO -D_UNICODE -DwxNO_UNSAFE_WXSTRING_CONV -DwxUSE_UNICODE -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/run/build/BambuStudio/src -I/run/build/BambuStudio/build/src/platform -I/run/build/BambuStudio/src/libslic3r -I/run/build/BambuStudio/build/src/libslic3r -I/run/build/BambuStudio/deps/build/destdir/usr/local/include/opencascade -I/run/build/BambuStudio/src/libnest2d/include -I/run/build/BambuStudio/src/miniz -I/run/build/BambuStudio/src/glu-libtess/include -I/run/build/BambuStudio/src/clipper2/Clipper2Lib/include -isystem /run/build/BambuStudio/src/eigen -isystem /run/build/BambuStudio/src/libigl -isystem /run/build/BambuStudio/deps/build/destdir/usr/local/include -isystem /run/build/BambuStudio/deps/build/destdir/usr/local/include/boost-1_78 -isystem /run/build/BambuStudio/deps/build/destdir/usr/local/include/OpenEXR -O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -fext-numeric-literals -Wall -Wno-reorder -O3 -DNDEBUG -std=gnu++17 -fPIC -fsigned-char -Werror=return-type -Wno-ignored-attributes -Wno-unknown-pragmas -DOPENVDB_ABI_VERSION_NUMBER=8 -MD -MT src/libslic3r/CMakeFiles/libslic3r.dir/GCode/RetractWhenCrossingPerimeters.cpp.o -MF src/libslic3r/CMakeFiles/libslic3r.dir/GCode/RetractWhenCrossingPerimeters.cpp.o.d -o src/libslic3r/CMakeFiles/libslic3r.dir/GCode/RetractWhenCrossingPerimeters.cpp.o -c /run/build/BambuStudio/src/libslic3r/GCode/RetractWhenCrossingPerimeters.cpp
In file included from /run/build/BambuStudio/src/libslic3r/GCode/RetractWhenCrossingPerimeters.cpp:2:
/run/build/BambuStudio/src/libslic3r/GCode/../Layer.hpp:153:29: error: field ‘loverhangs_bbox’ has incomplete type ‘Slic3r::BoundingBox’
  153 |     BoundingBox             loverhangs_bbox;
      |                             ^~~~~~~~~~~~~~~
In file included from /run/build/BambuStudio/src/libslic3r/GCode/../ExPolygon.hpp:4,
                 from /run/build/BambuStudio/src/libslic3r/GCode/../ClipperUtils.hpp:7,
                 from /run/build/BambuStudio/src/libslic3r/GCode/RetractWhenCrossingPerimeters.cpp:1:
/run/build/BambuStudio/src/libslic3r/GCode/../Point.hpp:17:7: note: forward declaration of ‘class Slic3r::BoundingBox’
   17 | class BoundingBox;
      |       ^~~~~~~~~~~