FIX: Fix missing std::regex declaration
/run/build/BambuStudio/src/libslic3r/FilamentGroupUtils.cpp: In lambda function:
/run/build/BambuStudio/src/libslic3r/FilamentGroupUtils.cpp:92:18: error: ‘regex’ is not a member of ‘std’
   92 |             std::regex r1(R"(^Sup.(\w+)$)");
      |                  ^~~~~