Fix missing BOOST_LOG_TRIVIAL declaration
/run/build/BambuStudio/src/libslic3r/Flow.cpp: In static member function ‘static float Slic3r::Flow::rounded_rectangle_extrusion_spacing(float, float)’:
/run/build/BambuStudio/src/libslic3r/Flow.cpp:194:27: error: ‘error’ was not declared in this scope; did you mean ‘nlohmann::detail::cbor_tag_handler_t::error’?
  194 |         BOOST_LOG_TRIVIAL(error)<< __FUNCTION__ << boost::format("negative extrusion : width %1%   height %2%") % width % height;
      |                           ^~~~~
      |                           nlohmann::detail::cbor_tag_handler_t::error