Fix missing std::regex declaration
/run/build/BambuStudio/src/slic3r/GUI/WebViewDialog.cpp: In member function ‘void Slic3r::GUI::WebViewPanel::SetMakerworldPageLoginStatus(bool, wxString)’:
/run/build/BambuStudio/src/slic3r/GUI/WebViewDialog.cpp:818:10: error: ‘regex’ is not a member of ‘std’; did you mean ‘boost::regex’?
  818 |     std::regex pattern("^https://.*/(.*/){0,1}agree-terms.*");
      |          ^~~~~