FIX: Fix missing boost::nowide::remove declaration
/run/build/BambuStudio/src/slic3r/GUI/Plater.cpp: In member function ‘void Slic3r::GUI::Plater::priv::on_helio_processing_complete(Slic3r::HelioCompletionEvent&)’:
/run/build/BambuStudio/src/slic3r/GUI/Plater.cpp:9263: error: ‘remove’ is not a member of ‘boost::nowide’
 9263 |         int deleted = boost::nowide::remove(a.tmp_path.c_str());