Fix ModelObject declaration
Forward declare ModelObject in bbs_3mf.hpp so this header can be
included in ModelObject.hpp where the class is actually defined,
the same way bbs_3mf.hpp also forward declares "class Model" and
others.

[274/471] Building CXX object src/slic3r/CMakeFiles/libslic3r_gui.dir/GUI/Printer/PrinterFileSystem.cpp.o
FAILED: src/slic3r/CMakeFiles/libslic3r_gui.dir/GUI/Printer/PrinterFileSystem.cpp.o
/run/ccache/bin/c++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CHRONO_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_IOSTREAMS_NO_LIB -DBOOST_LOCALE_NO_LIB -DBOOST_LOG_NO_LIB -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -DCURL_STATICLIB -DGLEW_STATIC -DLIBNEST2D_GEOMETRIES_libslic3r -DLIBNEST2D_OPTIMIZER_nlopt -DLIBNEST2D_STATIC -DLIBNEST2D_THREADING_tbb -DOPENSSL_CERT_OVERRIDE -DOPENVDB_OPENEXR_STATICLIB -DOPENVDB_STATICLIB -DSLIC3R_CURRENTLY_COMPILING_GUI_MODULE -DSLIC3R_GUI -DTBB_USE_CAPTURED_EXCEPTION=0 -DUNICODE -DUSE_TBB -DWXINTL_NO_GETTEXT_MACRO -D_FILE_OFFSET_BITS=64 -D_UNICODE -D__WXGTK3__ -D__WXGTK__ -DwxDEBUG_LEVEL=0 -DwxNO_UNSAFE_WXSTRING_CONV -DwxUSE_UNICODE -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/run/build/BambuStudio/src -I/run/build/BambuStudio/build/src/platform -I/run/build/BambuStudio/src/hidapi/include -I/run/build/BambuStudio/src/slic3r/Utils -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/run/build/BambuStudio/deps/build/destdir/usr/local/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/atk-1.0 -I/usr/include/blkid -I/usr/include/libmount -I/usr/include/sysprof-6 -I/run/build/BambuStudio/deps/build/destdir/usr/local/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/gio-unix-2.0 -I/usr/include/fribidi -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/gstreamer-1.0 -I/run/build/BambuStudio/build/src/libslic3r -I/run/build/BambuStudio/deps/build/destdir/usr/local/include/opencascade -I/run/build/BambuStudio/src/libnest2d/include -I/run/build/BambuStudio/src/miniz -I/run/build/BambuStudio/src/glu-libtess/include -I/run/build/BambuStudio/src/clipper2/Clipper2Lib/include -I/run/build/BambuStudio/src/minilzo -isystem /run/build/BambuStudio/src/eigen -isystem /run/build/BambuStudio/src/libigl -isystem /run/build/BambuStudio/deps/build/destdir/usr/local/lib/wx/include/gtk3-unicode-static-3.2 -isystem /run/build/BambuStudio/deps/build/destdir/usr/local/include/wx-3.2 -isystem /run/build/BambuStudio/deps/build/destdir/usr/local/include -isystem /run/build/BambuStudio/deps/build/destdir/usr/local/include/boost-1_78 -isystem /run/build/BambuStudio/deps/build/destdir/usr/local/include/OpenEXR -std=gnu++20 -fext-numeric-literals -Wall -Wno-reorder -pthread -O3 -DNDEBUG -std=gnu++17 -fPIC -fsigned-char -Werror=return-type -Wno-ignored-attributes -Wno-unknown-pragmas -DOPENVDB_ABI_VERSION_NUMBER=8 -MD -MT src/slic3r/CMakeFiles/libslic3r_gui.dir/GUI/Printer/PrinterFileSystem.cpp.o -MF src/slic3r/CMakeFiles/libslic3r_gui.dir/GUI/Printer/PrinterFileSystem.cpp.o.d -o src/slic3r/CMakeFiles/libslic3r_gui.dir/GUI/Printer/PrinterFileSystem.cpp.o -c /run/build/BambuStudio/src/slic3r/GUI/Printer/PrinterFileSystem.cpp
In file included from /run/build/BambuStudio/src/slic3r/GUI/Printer/PrinterFileSystem.cpp:3:
/run/build/BambuStudio/src/libslic3r/Format/bbs_3mf.hpp:264:13: error: variable or field ‘save_object_mesh’ declared void
  264 | extern void save_object_mesh(ModelObject& object);
      |             ^~~~~~~~~~~~~~~~
/run/build/BambuStudio/src/libslic3r/Format/bbs_3mf.hpp:264:30: error: ‘ModelObject’ was not declared in this scope
  264 | extern void save_object_mesh(ModelObject& object);
      |                              ^~~~~~~~~~~
/run/build/BambuStudio/src/libslic3r/Format/bbs_3mf.hpp:264:43: error: ‘object’ was not declared in this scope; did you mean ‘nlohmann::detail::value_t::object’?
  264 | extern void save_object_mesh(ModelObject& object);
      |                                           ^~~~~~

Closes: #3141