FIX: fix the compiling error under macos for previous patches
/Users/ci.slave/slicer/patch_build/1/bamboo_slicer/src/libslic3r/GCode/GCodeProcessor.cpp:486:33: error: cannot pass non-trivial object of type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') to variadic function; expected type from format string was 'char *' [-Wnon-pod-varargs]
                                  get_time_dhms(machine.time));
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~

github pull request: https://github.com/bambulab/BambuStudio/pull/3360
Change-Id: If13ee145b20ef9532b23a58bb3b0a29f30d8c0a8

Change-Id: I98fd87417c432c3afae67a3d2bc29c79f8bffa3c
(cherry picked from commit a2f3e654d696726dda3d3fe22a88e7e5b1fc73e8)