FIX: Fix missing intersection_pl declaration
/run/build/BambuStudio/src/libslic3r/Fill/FillLightning.cpp: In member function ‘virtual void Slic3r::FillLightning::Filler::_fill_surface_single(const Slic3r::FillParams&, unsigned int, const std::pair<float, Slic3r::Point>&, Slic3r::ExPolygon, Slic3r::Polylines&)’:
/run/build/BambuStudio/src/libslic3r/Fill/FillLightning.cpp:22:31: error: ‘intersection_pl’ was not declared in this scope
   22 |     Polylines all_polylines = intersection_pl(std::move(fill_lines), expolygon);
      |                               ^~~~~~~~~~~~~~~