FIX: Fix missing wxPanel declaration
In file included from /run/build/BambuStudio/src/slic3r/GUI/Widgets/LinkLabel.cpp:2:
/run/build/BambuStudio/src/slic3r/GUI/Widgets/LinkLabel.hpp:13:5: error: ‘wxPanel’ does not name a type; did you mean ‘wxPen’?
   13 |     wxPanel* m_underline{nullptr};
      |     ^~~~~~~
      |     wxPen