FIX: Fix missing wxNumberFormatter declaration
/run/build/BambuStudio/src/slic3r/GUI/GCodeRenderer/AdvancedRenderer.cpp:977: error: ‘wxNumberFormatter’ has not been declared
  977 |                                                     _L("Loading gcode data") + ": " + wxNumberFormatter::ToString(progress_value, 0, wxNumberFormatter::Style_None) + "%");