FIX: Fix missing std::set declaration
/run/build/BambuStudio/src/slic3r/GUI/EncodedFilament.hpp: At global scope:
/run/build/BambuStudio/src/slic3r/GUI/EncodedFilament.hpp:81:10: error: ‘set’ in namespace ‘std’ does not name a template type
   81 |     std::set<wxColour, wxColorSorter> m_colors;
      |          ^~~
/run/build/BambuStudio/src/slic3r/GUI/EncodedFilament.hpp:13:1: note: ‘std::set’ is defined in header ‘<set>’; this is probably fixable by adding ‘#include <set>’
   12 | #include <chrono>
  +++ |+#include <set>
   13 |