FIX: Fix missing diff/intersection/etc. declaration
/run/build/BambuStudio/src/libslic3r/PrintApply.cpp:313:28: error: ‘diff’ was not declared in this scope
  313 |             Polygons res = diff(printable_poly, poly);
      |                            ^~~~
/run/build/BambuStudio/src/libslic3r/PrintApply.cpp:317:39: error: ‘intersection’ was not declared in this scope; did you mean ‘Slic3r::line_alg::intersection’?
  317 |         Polygons all_extruder_polys = intersection({printable_poly}, extruder_polys);
      |                                       ^~~~~~~~~~~~
      |                                       Slic3r::line_alg::intersection
In file included from /run/build/BambuStudio/src/libslic3r/Polygon.hpp:7,
                 from /run/build/BambuStudio/src/libslic3r/BoundingBox.hpp:7,
                 from /run/build/BambuStudio/src/libslic3r/Geometry.hpp:5,
                 from /run/build/BambuStudio/src/libslic3r/Model.hpp:6:
/run/build/BambuStudio/src/libslic3r/Line.hpp:123:24: note: ‘Slic3r::line_alg::intersection’ declared here
  123 | template<class L> bool intersection(const L &l1, const L &l2, Vec<Dim<L>, Scalar<L>> *intersection_pt)
      |                        ^~~~~~~~~~~~
/run/build/BambuStudio/src/libslic3r/PrintApply.cpp: In lambda function:
/run/build/BambuStudio/src/libslic3r/PrintApply.cpp:323:22: error: ‘intersection’ is not captured
  323 |                 if (!intersection(poly, contours[i]).empty()) { result.insert(static_cast<int>(i)); }
      |                      ^~~~~~~~~~~~