FIX: Fix missing wxWHITE declaration
/run/build/BambuStudio/src/slic3r/GUI/Widgets/StateColor.cpp: In static member function ‘static StateColor StateColor::createButtonStyleGray()’:
/run/build/BambuStudio/src/slic3r/GUI/Widgets/StateColor.cpp:195:35: error: ‘wxWHITE’ was not declared in this scope
  195 |         std::pair<wxColour, int>(*wxWHITE, StateColor::Focused),
      |                                   ^~~~~~~